#!/usr/bin/env python
# coding: utf-8

# In[1]:


import sqlite3

import pandas as pd


# In[2]:


conn = sqlite3.connect(r"U:\\Giacomo\DataBase\first.db")


# In[3]:


df = pd.read_csv(r"U:\\Giacomo\DataBase\EmAberto.csv")


# In[13]:


#print(df)
                


# In[5]:


cursor = conn.cursor()


# In[7]:


#################### Essa parte do código cria o banco de dados ################################


#df.to_sql("EmAberto", conn)


# In[10]:


dados = cursor.execute("""SELECT COUNT(*) FROM EmAberto""").fetchall()


# In[25]:


print(dados[0][0])


# In[9]:


for i in dados:
    print(i)
    print('\n')

